<?php
/**
 * Metator (http://metator.com/)
 * @copyright  Copyright (c) 2013 Vehicle Fits, llc
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

if ($this->pageCount) {
    ?>
    <div class="pagination pagination-centered">
        <ul>
            <!-- Previous page link -->
            <?php
            if (isset($this->previous)) {
                $params = array('page'=>$this->previous) + $_GET;
                ?>
                <li>
                    <a href="?<?=http_build_query($params)?>"><<</a>
                </li>
                <?php
            } else {
                ?>
                <li class="disabled">
                    <a href="#"><<</a>
                </li>
                <?php
            }
            ?>

            <!-- Numbered page links -->
            <?php
            foreach ($this->pagesInRange as $page) {
                if ($page != $this->current) {
                    $params = array('page'=>$page) + $_GET;
                    ?>
                    <li>
                        <a href="?<?=http_build_query($params)?>"><?php echo $page; ?></a>
                    </li>
                    <?php
                } else {
                    ?>
                    <li class="active"><a href="#"><?php echo $page; ?></a></li>
                    <?php
                }
            }
            ?>

            <!-- Next page link -->
            <?php
            if (isset($this->next)) {
                $params = array('page'=>$this->next) + $_GET;
                ?>
                <li>
                    <a href="?<?=http_build_query($params)?>">>></a>
                </li>
                <?php
            } else {
                ?>
                <li class="disabled">
                    <a href="#">>></a>
                </li>
                <?php
            }
            ?>
        </ul>
    </div>
    <?php
}