language: php

services:
  - mysql

php:
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php -- --quiet
  - php composer.phar install --dev --prefer-source

script:
  - vendor/bin/phpunit