<?php
/**
 * Metator (http://metator.com/)
 * @copyright  Copyright (c) 2013 Vehicle Fits, llc
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

function renderCategories($categories, $view) {
    ob_start();
    ?>
    <ul class="nav nav-list">
        <?php
        foreach($categories as $category) {
            ?>
            <li><a href="<?=$view->url('category', $category)?>"><?=$view->escapeHTML($category['name'])?></a></li>
            <?php
            if(count($category['children'])) {
                echo renderCategories($category['children'], $view);
            }
        }
        ?>
    </ul>
    <?php
    return ob_get_clean();
}
?>
<div class="well sidebar-nav">
    <?php
    echo renderCategories($categories, $this);
    ?>
</div><!--/.well -->