<a class="btn" href="<?=$this->url('category_new')?>">New</a>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Parents</th>
        </tr>
    </thead>
    <?php
    foreach($this->categories as $category) {
        ?>
        <tr>
            <td><?=$this->escapeHTML($category['id'])?></td>
            <td><?=$this->escapeHTML($category['name'])?></td>
            <td><?=$this->escapeHTML(implode(',',$category['parents']))?></td>
        </tr>
        <?php
    }
    ?>
</table>