<?php
/**
 * Metator (http://metator.com/)
 * @copyright  Copyright (c) 2013 Vehicle Fits, llc
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<h1><?=$this->escapeHTML($category)?></h1>

<?=$this->partial('product/product/list.phtml',array(
    'products'=>$products
));?>

<div class="pull-left">
    <?php
    if($total>1000) {
        printf('Listing %d-%d of about %s', $start, $end, number_format(round($total,-3)));
    } else {
        printf('Listing %d-%d of %s', $start, $end, number_format($total));
    }
    ?>
</div>

<div class="pull-right">
    <?php
    echo $this->paginationControl(
        $this->paginator,
        'sliding',
        // the partial to use to render the control
        array('application/pagination.phtml', '')
    );
    ?>
</div>