<?php
$this->headTitle('Edit Product');
$this->headScript()->appendFile('/js/jquery.metadata.pack.js');
$this->headScript()->appendFile('/js/product-form.js');
?>
<h1>Editing Product</h1>
<?php
$form->setView(new \Zend_View);
$form->addElement('submit','save',[
    'label'=>'Save',
    'class'=>'btn'
]);
$form->addElement('submit','save_and_continue',[
    'label'=>'Save & Continue',
    'class'=>'btn'
]);
echo $form;
?>
<fieldset class="well">
    <label>Images</label>
    <?php
    foreach($product->getImageHashes() as $image_hash) {
        ?>
        <a href="/image/<?=$image_hash?>"><img src="/image/150x150/<?=$image_hash?>" /></a>
    <?php
    }
    ?>
</fieldset>