<?php
/**
 * Metator (http://metator.com/)
 * @copyright  Copyright (c) 2013 Vehicle Fits, llc
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$this->headTitle('Edit Product');
$this->headScript()->appendFile('/js/jquery.metadata.pack.js');

$form->addElement('submit','save',[
    'label'=>'Save',
    'class'=>'btn'
]);
$form->addElement('submit','save_and_continue',[
    'label'=>'Save & Continue',
    'class'=>'btn'
]);

foreach($form->getElements() as $element) {
    $element->setView(new \Zend_View);
};
?>
<h1>Editing Product</h1>
<form action="?" method="post" enctype="multipart/form-data">
    <div class="pull-right product-edit-controls">
        <?php
        echo $form->save_and_continue;
        echo $form->save;
        ?>
    </div>
    <ul class="nav nav-tabs" id="productTabs">
        <li><a href="#general" data-toggle="tab">General</a></li>
        <li><a href="#images" data-toggle="tab">Images</a></li>
        <li><a href="#attributes" data-toggle="tab">Attributes</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="general">
            <div class="row-fluid">
                <div class="span6">
                    <?php
                    echo $form->sku;
                    echo $form->name;
                    echo $form->description;
                    ?>
                </div>
                <div class="span6">
                    <?php
                    echo $form->basePrice;
                    echo $form->categories;
                    ?>
                </div>
            </div>
        </div>
        <div class="tab-pane" id="images">
            <ul>
            <?php
            foreach($product->getImageHashes() as $image_hash) {
                ?>
                <li>
                    <a href="/image/<?=$image_hash?>"><img src="/image/150x150/<?=$image_hash?>" /></a>
                    <input type="radio" name="default_image" value="<?=$image_hash?>" /> Is Default?
                </li>
                <?php
            }
            ?>
            </ul>
            <?php
            echo $form->image_to_add;
            ?>
        </div>
        <div class="tab-pane" id="attributes">
            <strong>Existing Attributes</strong>
            <?php
            foreach($product->attributes() as $attribute => $value) {
                ?>
                <dt>
                    <label for="attribute_<?=$this->escapeHtmlAttr($attribute)?>"><?=$this->escapeHTML($attribute)?></label>
                </dt>
                <dd>
                    <input type="text" name="attribute_<?=$this->escapeHtmlAttr($attribute)?>" value="<?=$this->escapeHtmlAttr($value)?>" />
                    <!--<input type="checkbox" name="delete_<?=$this->escapeHtmlAttr($attribute)?>" value="1" /> Delete?-->
                </dd>
                <?php
            }
            ?>
            <hr />
            <strong>Add New Attribute</strong>
            <dt><label for="new_attribute_label">Label</label></dt>
                <dd><input type="text" name="new_attribute_label" value="" /></dd>
            <dt><label for="new_attribute_value">Value</label></dt>
            <dd><input type="text" name="new_attribute_value" value="" /></dd>
        </div>
    </div>

</form>

<script>
    $(function () {
        $('#productTabs a:first').tab('show');
    })
</script>