<?php
$this->plugin("currencyformat")->setCurrencyCode("USD")->setLocale("en_US");
?>
<div class="row-fluid">
<?php
$i = 0;
foreach($this->products as $product) {
    if($i%3==0) {
        echo '</div><div class="row-fluid">';
    }
    ?>
    <div class="span4 product-block outline">
        <a href="<?=$this->productURL($product->id())?>"><h2><?=$this->escapeHTML($product->getName())?></h2></a>

        <?php
        echo '<a href="'.$this->productURL($product->id()).'">';
        if(!$product->getDefaultImageHash()) {
            echo '<img src="http://placehold.it/150x150" />';
        } else {
            echo '<img src="/image/150x150/'.$product->getDefaultImageHash().'" />';
        }
        echo '</a>';
        ?>
        <p><?=$this->currencyFormat($product->price())?></p></a>
        <p><?=$this->escapeHTML($product->getDescription())?></p>
        <p>
            <a class="btn btn-success" href="<?=$this->url('cart_add',array('id'=>$product->id()))?>">
                <i class="icon-shopping-cart icon-white icon-large"></i>
                Add To Cart
            </a>
        </p>
    </div>
    <?php
    $i++;
}
?>
</div>