<?php
$this->plugin("currencyformat")->setCurrencyCode("USD")->setLocale("en_US");
?>
<div class="row-fluid">
<?php
$i = 0;
foreach($this->products as $product) {
    if($i%3==0) {
        echo '</div><div class="row-fluid">';
    }
    ?>
    <div class="span4 product-block">
        <a href="<?=$this->productURL($product->id())?>"><h2><?=$this->escapeHTML($product->getName())?></h2></a>
        <?=$this->currencyFormat($product->price())?>
        <?php
        foreach($product->getImageHashes() as $image_hash) {
            echo '<img src="/image/150x150/'.$image_hash.'" />';
        }
        ?>
        <p>put description</p>
        <p>
            <a class="btn" href="<?=$this->productURL($product->id())?>">View details &raquo;</a>
            <a class="btn btn-primary" href="<?=$this->url('cart_add',array('id'=>$product->id()))?>">Add To Cart</a>
        </p>
    </div>
    <?php
    $i++;
}
?>
</div>