<?php
/**
 * Metator (http://metator.com/)
 * @copyright  Copyright (c) 2013 Vehicle Fits, llc
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<a class="btn btn-success" href="/product/new"><i class="icon-plus-sign"></i> Add New</a>

<a class="btn" href="<?=$this->url('product_export')?>"><i class="icon-cloud-download"></i> Export</a>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th></th>
            <th>ID</th>
            <th>SKU</th>
            <th>Name</th>
            <th>Price</th>
        </tr>
    </thead>
    <?php
    foreach($this->products as $product) {
        ?>
        <tr>
            <td>
                <a href="<?=$this->url('product_edit',array('id'=>$product->id()))?>" class="btn"><i class="icon-pencil"></i> Edit</a>
                <a href="<?=$this->url('product_deactivate',array('id'=>$product->id()))?>" class="btn btn-danger"><i class="icon-remove-sign"></i> Deactivate</a>
            </td>
            <td><?=$this->escapeHTML($product->id())?></td>
            <td><?=$this->escapeHTML($product->getSku())?></td>
            <td><?=$this->escapeHTML($product->getName())?></td>
            <td><?=$this->escapeHTML($product->getBasePrice())?></td>
        </tr>
        <?php
    }
    ?>
</table>

<div class="pull-left">
    <?php
    if($total>1000) {
        printf('Listing %d-%d of about %s', $start, $end, number_format(round($total,-3)));
    } else {
        printf('Listing %d-%d of %s', $start, $end, number_format($total));
    }
    ?>
</div>

<div class="pull-right">
    <?php
    echo $this->paginationControl(
        $this->paginator,
        'sliding',
        // the partial to use to render the control
        array('application/pagination.phtml', '')
    );
    ?>
</div>