<div class="well sidebar-nav">
    <ul class="nav nav-list">
        <li class="nav-header">Product</li>
        <li class="active"><a href="#">Edit</a></li>
        <li><a href="#">List</a></li>
        <li><a href="#">Delete</a></li>
        <li><a href="#">Create</a></li>
        <li class="nav-header">Categories</li>
        <li><a href="#">List</a></li>
        <li><a href="#">Edit</a></li>
        <li><a href="#">Delete</a></li>
        <li><a href="#">Create</a></li>
        <li class="nav-header">System</li>
        <li><a href="#">Cache</a></li>
        <li><a href="#">Search Index</a></li>
        <li><a href="#">Configuration Settings</a></li>
    </ul>
</div><!--/.well -->