<div class="well sidebar-nav">
    <ul class="nav nav-list">
        <li class="nav-header">Shirts</li>
        <li class="active"><a href="#">Cotton</a></li>
        <li><a href="#">Polyester</a></li>
        <li><a href="#">Silk</a></li>
        <li><a href="#">T-Shirts</a></li>
        <li class="nav-header">Pants</li>
        <li><a href="#">Jeans</a></li>
        <li><a href="#">Shorts</a></li>
        <li><a href="#">Dress Pants</a></li>
    </ul>
</div><!--/.well -->