<a class="btn" href="/product/new">New</a>

<table class="table table-bordered">
    <thead>
        <th>ID</th>
        <th>SKU</th>
        <th>Name</th>
        <th>Price</th>
    </thead>
    <?php
    foreach($this->products as $product) {
        ?>
        <tr>
            <td><?=$this->escapeHTML($product->id())?></td>
            <td><?=$this->escapeHTML($product->getSku())?></td>
            <td><?=$this->escapeHTML($product->getName())?></td>
            <td><?=$this->escapeHTML($product->getBasePrice())?></td>
        </tr>
        <?php
    }
    ?>
</table>