<?php echo $this->doctype() ?>
<html>
<head>
    <?php echo $this->headTitle() ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
    <style type="text/css">
        body {
            padding-top: 60px;
            padding-bottom: 40px;
        }
        .sidebar-nav {
            padding: 9px 0;
        }

        @media (max-width: 980px) {
            /* Enable use of floated navbar text */
            .navbar-text.pull-right {
                float: none;
                padding-left: 5px;
                padding-right: 5px;
            }
        }
        .hero-unit p {
            font-size:15px;
        }
        .hero-unit {
            padding-top:10px;
            padding-bottom:10px;
        }
        .zend_form{
            background:#fff;
            width:460px;
            padding:0;
            overflow:auto;
        }

        .zend_form dt{
            padding:0;
            clear:both;
            width:30%;
            float:left;
            text-align:right;
            margin:5px 5px 5px 0;
        }

        .zend_form dd{
            padding:0;
            float:left;
            width:68%;
            margin:5px 2px 5px 0;
        }

        .zend_form p{
            padding:0;
            margin:0;
        }

        .zend_form input, .zend_form textarea{
            margin:0 0 2px 0;
            padding:0;
        }

        .submit{
            float:right;
        }

        .required:before{content:'*'}
    </style>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="#">Metator</a>
            <div class="nav-collapse collapse">
                <p class="navbar-text pull-right">
                    Logged in as <a href="#" class="navbar-link">Username</a>
                </p>
                <ul class="nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <?php echo $this->layout()->navigation ?>
        </div><!--/span-->
        <div class="span9">
            <?php echo $this->layout()->splash ?>
            <?php echo $this->layout()->content ?>
        </div><!--/span-->
    </div><!--/row-->

    <hr>

    <footer>
        <p>&copy; Company 2013</p>
    </footer>

</div><!--/.fluid-container-->

</body>
</html>