<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Metator '. $this->translate('Demo'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

</head>
<body class="admin">

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span2">
            <?=$this->partial('layout/admin-navigation.phtml',array(
                'controller'=>$this->controller
            ))?>
        </div>
        <div class="span10">
            <?php echo $this->content; ?>
        </div>
    </div>
    <hr>

    <footer>
        <p>&copy; Vehicle Fits, llc 2013</p>
    </footer>

</div><!--/.fluid-container-->


<?php echo $this->inlineScript() ?>
</body>
</html>
