<?php
/**
 * Metator (http://metator.com/)
 * @copyright  Copyright (c) 2013 Vehicle Fits, llc
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <?=$this->partial('layout/head.phtml')?>
</head>
<body class="admin">

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <a href="/">&laquo; Back To Frontend</a>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span2">
            <?=$this->partial('layout/admin-navigation.phtml',array(
                'controller'=>$this->controller
            ))?>
        </div>
        <div class="span10">
            <?=$this->partial('layout/messages.phtml')?>
            <?php echo $this->content; ?>
        </div>
    </div>
    <?=$this->partial('layout/footer.phtml')?>

</div><!--/.fluid-container-->


<?php echo $this->inlineScript() ?>
</body>
</html>
