<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <?=$this->partial('layout/head.phtml')?>
</head>
<body class="admin">

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span2">
            <?=$this->partial('layout/admin-navigation.phtml',array(
                'controller'=>$this->controller
            ))?>
        </div>
        <div class="span10">
            <?php echo $this->content; ?>
        </div>
    </div>
    <hr>

    <footer>
        <p>&copy; Vehicle Fits, llc 2013</p>
    </footer>

</div><!--/.fluid-container-->


<?php echo $this->inlineScript() ?>
</body>
</html>
