<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <?=$this->partial('layout/head.phtml')?>
    </head>
    <body>

        <?=$this->partial('layout/navigation.phtml')?>

        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span3">
                    <?=$this->categoryStructure()?>
                </div><!--/span-->
                <div class="span9">
                    <?php echo $this->splash; ?>
                    <?php echo $this->content; ?>
                </div><!--/span-->
            </div><!--/row-->

            <hr>

            <footer>
                <p>&copy; Vehicle Fits, llc 2013</p>
            </footer>

        </div><!--/.fluid-container-->


        <?php echo $this->inlineScript() ?>
    </body>
</html>
