<?php
/**
 * Metator (http://metator.com/)
 * @copyright  Copyright (c) 2013 Vehicle Fits, llc
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <?=$this->partial('layout/head.phtml')?>
    </head>
    <body>

        <?=$this->partial('layout/navigation.phtml')?>

        <div class="container-fluid">
            <?php echo $this->content; ?>
            <?=$this->partial('layout/footer.phtml')?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
