<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <?=$this->partial('layout/head.phtml')?>
    </head>
    <body>

        <?=$this->partial('layout/navigation.phtml')?>

        <div class="container-fluid">

            <?php echo $this->content; ?>

            <hr>

            <footer>
                <p>&copy; Vehicle Fits, llc 2013</p>
            </footer>

        </div><!--/.fluid-container-->


        <?php echo $this->inlineScript() ?>
    </body>
</html>
