<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="brand" href="<?=$this->url('home')?>">Metator</a>

            <div class="nav-collapse collapse">
                <p class="navbar-text pull-right">
                    <!-- Test if the User is connected -->
                    <?php
                    if(!$this->zfcUserIdentity()) {
                        ?>
                        <!-- display the login form -->
                        <?php ''/* echo $this->zfcUserLoginWidget(array('redirect'=>'application'));*/ ?>
                        <a class="btn btn-mini" href="<?=$this->url('zfcuser/login')?>">Login</a>
                        <?php
                    } else {
                        ?>
                        <!-- display the 'display name' of the user -->
                        Welcome,
                        <a class="navbar-link" href="<?=$this->url('zfcuser')?>"><?php echo $this->zfcUserIdentity()->getEmail(); ?></a>
                        <a class="btn btn-mini" href="<?=$this->url('zfcuser/logout')?>">Logout</a>
                        <?php
                    }

                    $session = new \Zend\Session\Container('metator');
                    $cart = $session->cart;

                    echo '<a class="btn btn-mini" href="'.$this->url('cart').'">';
                    if($cart) {
                        $this->plugin("currencyformat")->setCurrencyCode("USD")->setLocale("en_US");
                        printf('%d item(s) (%s)', $cart->itemCount(), $this->currencyFormat($cart->totalPrice()));
                    } else {
                        echo '0 Items In Cart';
                    }
                    echo '</a>';
                    ?>
                </p>
                <ul class="nav">
                    <li class="active"><a href="<?=$this->url('home')?>">Home</a></li>
                    <li <?=$this->controller=='product' ? 'class="active"' : ''?>><a href="/product/manage">Manage Products</a></li>
                    <li <?=$this->controller=='category' ? 'class="active"' : ''?>><a href="/category/manage">Manage Categories</a></li>
                    <li <?=$this->controller=='attribute' ? 'class="active"' : ''?>><a href="/attribute/manage">Manage Attributes</a></li>
                </ul>
            </div><!--/.nav-collapse -->

        </div>
    </div>
</div>