<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="brand" href="<?=$this->url('home')?>">Metator</a>

            <div class="nav-collapse collapse">
                <p class="navbar-text pull-right">
                    Logged in as <a href="#" class="navbar-link">Username</a>
                </p>
                <ul class="nav">
                    <li class="active"><a href="<?=$this->url('home')?>">Home</a></li>
                    <li <?=$this->controller=='product' ? 'class="active"' : ''?>><a href="/product/manage">Manage Products</a></li>
                    <li <?=$this->controller=='category' ? 'class="active"' : ''?>><a href="/category/manage">Manage Categories</a></li>
                    <li <?=$this->controller=='attribute' ? 'class="active"' : ''?>><a href="/attribute/manage">Manage Attributes</a></li>
                </ul>
            </div><!--/.nav-collapse -->

        </div>
    </div>
</div>