<?php
$this->plugin("currencyformat")->setCurrencyCode("USD")->setLocale("en_US");
?>
<form action="<?=$this->url()?>" method="post">
    <table class="table table-bordered">
        <thead>
            <th>Item</th>
            <th>Quantity</th>
            <th>Item Price</th>
            <th>Total Price</th>
        </thead>
        <tbody>
        <?php
        foreach($cart->items() as $item) {
            $product = $this->product($item);
            ?>
            <tr>
                <td>
                    <a href="<?=$this->productURL($item)?>">
                        <img src="/image/100x100/<?=$product->getDefaultImageHash()?>" />
                        <?=$this->escapeHTML($this->productName($item))?>
                    </a>
                </td>
                <td><input type="text" name="quantity-<?=$this->escapeHtmlAttr($item)?>" value="<?=$this->escapeHtmlAttr($cart->quantity($item))?>" /></td>
                <td><?=$this->currencyFormat($cart->price($item))?></td>
                <td><?=$this->currencyFormat($cart->totalPrice($item))?></td>
            </tr>
            <?php
        }
        ?>
        </tbody>
        <tfoot>
        <tr>
            <td colspan="4" class="summary">
                <dt>Grand Total</dt>
                    <dd><?=$this->currencyFormat($cart->totalPrice())?></dd>
            </td>
        </tr>
        <tr>
            <td colspan="4" class="actions">

                <button type="submit" name="update" value="1" class="btn btn-large btn-primary">
                    <i class="icon-save icon-white icon-large"></i>
                    Save
                </button>
                <button type="submit" name="checkout" value="1" class="btn btn-success btn-large pull-right">
                    <i class="icon-shopping-cart icon-white icon-large"></i>
                    Checkout
                </button>
            </td>
        </tr>
        </tfoot>
    </table>
</form>