<?php
$this->plugin("currencyformat")->setCurrencyCode("USD")->setLocale("en_US");
?>
<form action="<?=$this->url()?>" method="post">
    <table class="table table-bordered">
        <thead>
            <th>Item</th>
            <th>Quantity</th>
            <th>Item Price</th>
            <th>Total Price</th>
        </thead>
        <tbody>
        <?php
        foreach($cart->items() as $item) {
            ?>
            <tr>
                <td><a href="<?=$this->productURL($item)?>"><?=$this->escapeHTML($this->productName($item))?></a></td>
                <td><input type="text" name="quantity-<?=$this->escapeHtmlAttr($item)?>" value="<?=$this->escapeHtmlAttr($cart->quantity($item))?>" /></td>
                <td><?=$this->currencyFormat($cart->price($item))?></td>
                <td><?=$this->currencyFormat($cart->totalPrice($item))?></td>
            </tr>
            <?php
        }
        ?>
        </tbody>
        <tfoot>
        <tr>
            <td colspan="4" class="summary">
                <dt>Grand Total</dt>
                    <dd><?=$this->currencyFormat($cart->totalPrice())?></dd>
            </td>
        </tr>
        <tr>
            <td colspan="4" class="actions">
                <input type="submit" name="update" value="Update" class="btn btn-large" />
                <input type="submit" name="checkout" value="Checkout" class="btn btn-primary btn-large" />
            </td>
        </tr>
        </tfoot>
    </table>
</form>