<div class="hero-unit">
    <h1>Metator</h1>
    <p>A unit tested shopping cart.</p>
    <p>Why yet another open source shopping cart? There is a need for online retailers to sell complex products in today's marketplace. Configurable products that come in different colors & sizes like a T-Shirt, and groups of these configurable products like a product representing a T-Shirt & Pants sold together.</p>
    <p>Existing solutions for this like Magento lack the ability to import this complex data, and are hard to modify beyond it's cookie cutter functionality.</p>
    <p><a href="http://metator.com" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<?=$this->another_child?>