<?php
/**
 * Metator (http://metator.com/)
 * @copyright  Copyright (c) 2013 Vehicle Fits, llc
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

echo $this->partial('product/product/list.phtml',array(
    'products'=>$products
));

printf('Listing %d-%d of about %s', $start, $end, number_format(round($total,-3)));
echo $this->paginationControl(
    $this->paginator,
    'sliding',
    // the partial to use to render the control
    array('application/pagination.phtml', '')
);