<div class="well well-small">
    <?php
    if(!$this->zfcUserIdentity()) {
        ?>
        <?php echo $this->zfcUserLoginWidget(array('redirect'=>$this->url())); ?>
        Register and save time!
        Register with us for future convenience:

        Fast and easy check out
        Easy access to your order history and status
        <?php
    } else {
        ?>
        <strong>Welcome</strong>
        <a class="navbar-link" href="<?=$this->url('zfcuser')?>"><?php echo $this->zfcUserIdentity()->getEmail(); ?></a>
        <a class="btn btn-mini" href="<?=$this->url('zfcuser/logout')?>?redirect=<?=$this->escapeHTMLAttr($this->url())?>">Logout</a>
        <?php
    }
    ?>
</div>

<div class="row-fluid">
    <div class="span6">
        <?php
        $form->shipping->setView(new \Zend_View);
        echo $form->shipping;
        ?>
    </div><div class="span6">
        <?php
        $form->billing->setView(new \Zend_View);
        echo $form->billing;
        ?>
    </div>
</div>